PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX chemspider: <http://rdf.chemspider.com/#>
PREFIX sio: <http://semanticscience.org/resource/>
PREFIX chembl: <http://rdf.farmbio.uu.se/chembl/onto/#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
SELECT ?compound_name ?target_name ?target_organism ?csid_uri ?smiles ?inchi ?inchi_key ?std_type ?relation ?std_value ?std_unit ?molweight ?num_ro5_violations 
WHERE {
	GRAPH <http://www.conceptwiki.org> {
		?cw_uri skos:prefLabel ?compound_name.
	}
	GRAPH <http://www.chemspider.com> {
		?csid_uri chemspider:smiles ?inchi;
			chemspider:inchikey ?inchi_key;
			chemspider:smiles ?smiles . 
	}
	GRAPH <http://data.kasabi.com/dataset/chembl-rdf> {
		?activity_uri chembl:forMolecule ?chembl_uri ;
			chembl:type ?std_type ;
			chembl:relation ?relation ;
			chembl:standardValue ?std_value ;
			chembl:standardUnits ?std_unit ;
			chembl:onAssay ?assay_uri .
		?assay_uri chembl:hasTarget ?target_uri .
		?target_uri dc:title ?target_name ;
			chembl:organism ?target_organism .
		OPTIONAL { ?chembl_uri sio:CHEMINF_000200 _:node1 . 
			_:node1 a sio:CHEMINF_000314 ;
				sio:SIO_000300 ?num_ro5_violations }
		OPTIONAL { ?chembl_uri sio:CHEMINF_000200 _:node2 . 
			_:node2 a sio:CHEMINF_000198 ;
				sio:SIO_000300 ?molweight }
		
	}
}
